config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "roles#index"

  # get "/roles", to: "roles#index"
  # get "/roles/:id", to: "roles#show"
  # above lines replaced by:
  resources :roles do
    resources :logentries
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/logentry.rb
class Logentry < ApplicationRecord
  VALID_TYPES = ['Manual', 'System']
  validates :entry_type, inclusion: { in: VALID_TYPES }
  validates :body, presence: true
  belongs_to :role
end

app/models/role.rb
class Role < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true

  VALID_STATUSES = ['Lead', 'Interviewing', 'Bailed', 'Waiting']
  validates :status, inclusion: { in: VALID_STATUSES }
  
  has_many  :logentries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logentries_controller.rb
class LogentriesController < ApplicationController
  def create
    @role = Role.find(params[:role_id])
    @logentry = @role.logentries.create(logentry_params)
    redirect_to role_path(@role)
  end

  private
    def logentry_params
      params.require(:logentry).permit(:entry_type, :body)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all.order("updated_at DESC")
    @roles_count = @roles.count
  end

  def show
    @role = Role.find(params[:id])
  end

  def new
      @role = Role.new
  end

  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    @role = Role.find(params[:id])

    if @role.update(role_params)
      redirect_to @role
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def role_params
      params.require(:role).permit(:title, :notes, :status, :url)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobHunt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      

      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <h2 class="display-6 role-header">Job Hunt 🎯</h2>
        </a>
    </header>

      <%= yield %>
    </div>
  </body>

</html>

app/views/logentries/_form.html.erb
<%= form_with model: [ @role, @role.logentries.build ] do |form| %>

 
    <div class="mb-2">
      <%= form.select :entry_type, ['Manual', 'System'] %>
    </div>
    <div class="mb-2">
      <%= form.text_area :body, { class: "form-control", placeholder: "body" } %>
    </div>
  
  <div class="btn-group" role="group">
    <%= form.submit "Save", class: "btn btn-secondary btn-sm" %>
    <%= link_to "Cancel", @role, class: "btn btn-dark btn-sm" %>
  </div>

<% end %>

app/views/logentries/_logentry.html.erb
  <li class="logentry-list-group-item">
    <span class=""><%= logentry.entry_type %></span> - <span><%= logentry.body %></span>
  </li>

app/views/roles/_form.html.erb
<%= form_with model: role do |form| %>

  <div>

    <div class="mb-2">
      <%= form.select :status, ['Lead', 'Interviewing', 'Bailed', 'Waiting'] %>
    </div>
    <div class="mb-2">
      <%= form.text_field :title, { class: "form-control", placeholder: "title of the role" } %>
      <% role.errors.full_messages_for(:title).each do |message| %>
        <div class="message"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-2">
      <%= form.text_area :notes, { class: "form-control", placeholder: "notes" } %>
      <% role.errors.full_messages_for(:notes).each do |message| %>
        <div class="message"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-2">
      <%= form.text_area :url, { class: "form-control", placeholder: "URL to the role description" } %>
      <% role.errors.full_messages_for(:url).each do |message| %>
        <div class="message"><%= message %></div>
      <% end %>
    </div>

    <div class="btn-group" role="group">
      <%= form.submit "Save", class: "btn btn-secondary btn-sm" %>
      <%= link_to "Cancel", role, class: "btn btn-dark btn-sm" %>
    </div>
  </div>

<% end %>

app/views/roles/_role_card.html.erb
<div class="col">  
  <div class="card text-bg-dark mb-3" style="max-width: 20rem;">
    <a href="<%= role_path(role) %>">
      <div class="card-header">
        <h5><%= role.title %></h5>
      </div>
      
      <div class="card-body">
        <small class="badge pill bg-secondary role-status-<%= role.status.downcase %>">
          <%= role.status %>
        </small>
        <p class="card-text"><%= role.notes.truncate(100) %></p>
      </div>
      <div class="card-footer text-end">

        <div class="row">
          <div class="col-sm text-start">
            <span class="role-updated-at">
              <%= role.logentries.count %> log entries
            </span>
          </div>
          <div class="col-sm text-end">
            <span class="role-updated-at">
              <%= distance_of_time_in_words(role.updated_at, Time.now) %>
            </span>
          </div>
        </div>

      </div>
    </a>
  </div>
  
</div>

app/views/roles/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
    <li class="breadcrumb-item">
      <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">Roles</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      <%= @role.title %>
    </li>
  </ol>
</nav>

<div class="roles-form-container">
  <div class="row">
    <div class="col-3 text-end">
      <h3 class="role-sub-header">Edit</h3>
    </div>
    <div class="col-8">
      <%= render "form", role: @role %>
    </div>
    <div class="col-sm-2">
    </div>
  </div>
  <br /><br />
</div>

app/views/roles/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
   <li class="breadcrumb-item">
      <a class="link-body-emphasis fw-semibold text-decoration-none" href="/"><%= @roles_count %> Roles</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Listing
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      <%= link_to "Create a Role", new_role_path, class: "btn btn-secondary btn-sm" %>
    </li>
  </ol>
</nav>

<div class="row row-cols-1 row-cols-md-4 g-4">
    <% @roles.each do |role| %>
        <%= render "role_card", role: role %>
    <% end %>
  </div>
</div>

app/views/roles/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
    <li class="breadcrumb-item">
      <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">Roles</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      New!
    </li>
  </ol>
</nav>

<div class="roles-form-container">
  <div class="row">
    <div class="col-3 text-end">
      <h3 class="role-sub-header">Create</h3>
    </div>
    <div class="col-7">
      <%= render "form", role: @role %>
    </div>
    <div class="col-sm-2">
    </div>
  </div>
  <br /><br />
</div>

app/views/roles/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a class="link-body-emphasis fw-semibold text-decoration-none" href="/">Roles</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Entry
    </li>
  </ol>
</nav>

<div>

  <div class="row">

    <div class="col-sm-3">
      <h3 class="fw-bold mb-0 fs-4"><%= @role.title %></h3>
      <p><small class="badge bg-secondary role-status-<%= @role.status.downcase %>">
        <%= @role.status %>
      </small></p>

      <div class="btn-group" role="group">
        <%= link_to "Edit", edit_role_path(@role), class: "btn btn-secondary btn-sm" %>
        <%= link_to "Delete", @role, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark btn-sm" %>
      </div>

      <p>
        <small class="opacity-50 text-nowrap role-updated-at">
          Modified <%= distance_of_time_in_words(@role.updated_at, Time.now)%><br />
          Created <%= distance_of_time_in_words(@role.created_at, Time.now)%>
        </small>
      </p>
    </div>

    <div class="col-sm-9">
      <h3 class="role-sub-header">Notes:</h3>
      
      <p><%= @role.notes %></p>
      
      <div class="action-form">

        <div class="b-example-divider"></div>
        <div class="card-body actions">
          <h6>Log Entries</h6>
            <div>
              <ul class="logentry-list-group">                  
                <%= render @role.logentries %>
              </ul>
            </div>
        </div>

        <h6>Create</h6>
        <%= render 'logentries/form' %>

      </div>
    </div>

  </div>